name: Render RMarkdown Website
'on': push
jobs:
  build:
    runs-on: ubuntu-18.04
    container: rocker/geospatial:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "install.packages(c('testthat','RCurl','questionr'))"
          Rscript -e "questionr::qscan(list.files(pattern='*.R',recursive=T), load = TRUE, detail = FALSE)"
      - name: Render Site
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |-
          Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: docs
          GH_PAT: ${{ secrets.GH_PAT }}
          BRANCH: gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: docs